# Generated by Django 3.1.5 on 2021-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymimages',
            name='bg_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
