# Generated by Django 3.1.5 on 2021-01-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20210131_2103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymimages',
            new_name='Myimages',
        ),
    ]
