# Generated by Django 3.1.5 on 2021-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_post_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('file_name', models.FileField(upload_to='')),
                ('file_type', models.CharField(choices=[('exam', 'Exam file'), ('textbook', 'Textbook file')], default='exam', max_length=20)),
            ],
        ),
    ]
