# Generated by Django 3.1.5 on 2021-02-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20210204_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myimages',
        ),
    ]
