# Generated by Django 3.2.5 on 2021-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_delete_myimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=50)),
                ('team2_name', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
                ('week_day', models.CharField(max_length=50)),
                ('game_day', models.IntegerField()),
                ('game_month', models.IntegerField()),
                ('game_year', models.IntegerField()),
                ('team1_goals', models.IntegerField()),
                ('team2_goals', models.IntegerField()),
                ('match_status', models.CharField(choices=[('HT', 'HT'), ('FT', 'FT')], default='FT', max_length=20)),
                ('game_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_team', models.CharField(max_length=50)),
                ('player_no', models.IntegerField()),
                ('player_photo', models.ImageField(upload_to=None)),
                ('player_goals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_played', models.IntegerField()),
                ('team_win', models.IntegerField()),
                ('team_draw', models.IntegerField()),
                ('team_loose', models.IntegerField()),
                ('team_point', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Exam_dates',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
    ]
