# Generated by Django 3.2.5 on 2021-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20210821_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
