# Generated by Django 3.2.5 on 2021-08-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_player_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_photo',
        ),
    ]
