# Generated by Django 3.2.5 on 2021-11-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_remove_player_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='team_goal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
