# Generated by Django 3.2.5 on 2021-12-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_table_team_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_no',
            field=models.IntegerField(default=1),
        ),
    ]
