# Generated by Django 3.2.5 on 2022-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_game_game_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=50)),
                ('team2_name', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
                ('week_day', models.CharField(max_length=50)),
                ('game_day', models.IntegerField()),
                ('game_month', models.IntegerField()),
                ('game_year', models.IntegerField()),
                ('team1_goals', models.IntegerField()),
                ('team2_goals', models.IntegerField()),
                ('team1_Pen_goals', models.IntegerField(default=0)),
                ('team2_Pen_goals', models.IntegerField(default=0)),
                ('game_no', models.IntegerField(default=1)),
                ('match_status', models.CharField(choices=[('HT', 'HT'), ('FT', 'FT')], default='FT', max_length=20)),
                ('game_status', models.BooleanField(default=False)),
                ('game_pen', models.BooleanField(default=False)),
            ],
        ),
    ]
